languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Marco Molinati"
# copyright = "Marco Molinati"

[params]
  dateFormat = "2 January 2006"
  description = "Personal website of Marco Molinati"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Marco Molinati"
  # image = "img/author.jpg"
  headline = "Data Scientist &amp; AI Engineer"
  bio = "Data Scientist &amp; AI Engineer"
  links = [
    { instagram = "https://instagram.com/marco.molinati" },
    { github = "https://github.com/Moli2211" },
    { linkedin = "https://www.linkedin.com/in/marco-molinati-3403a2175/" },
  ]