languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Marco Molinati Website"
# copyright = "Marco Molinati"

[params]
  dateFormat = "2 January 2006"
  description = "Personal website of Marco Molinati, Data Scientist & AI Engineer"

[params.author]
  name = "Marco Molinati"
  image = "img/avatar.jpg"
  headline = "Data Scientist & AI Engineer"
  bio = "I am a Data Scientist & AI Engineer with a passion for harnessing data and AI to solve real-world problems. Currently working at Informatica, where I contribute to cutting-edge AI and data-driven projects."
  links = [
    { instagram = "https://instagram.com/marco.molinati" },
    { github = "https://github.com/Moli2211" },
    { linkedin = "https://www.linkedin.com/in/marco-molinati-3403a2175/" },
  ]